# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94bd1d15f75dd968668b97a3d6c2612f22e3a4fd59bb76cf1f200ef6042d8d580adea35353f66d0f93aa06dc480090da4ee4c0d57ee1c99e54b07ef97350aaf5

test:
  secret_key_base: 4cda21711d940e53c4e5292627851ab5cb1335c0e5006ad4c93d37404da8f8c53e9b771608aa961ac3565a09c19268913cd63d594389112f438d4611fb58355d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
